version: '3.1'

services:
  firstMariadb:
    container_name: mariadb-container
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root!
    ports:
      - 13306:3306
    volumes:
      - "/d/docker/database/mariadb/qbankdb/data:/var/lib/mysql"
    networks:
      default_bridge:
        ipv4_address: 172.27.0.10
networks:
  default_bridge:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16