# Logback configuration file
# logging.level.root=DEBUG
# mybatis mapper xml path
# mybatis:
#     mapper-locations: classpath:mappers/*.xml
# mybatis.mapper-locations=classpath:/my/work/multitenencydatabase/demo/**/sql/*.xml
