defaultTenent: tenant_1

spring:
    profiles:
        active: local
        include:
            - local-teamssvc
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

application:
    security:
        jwt:
            secret-key: 99d2485a2b601bc396cc378707ce3c6388b0d09be4c8f908f29c71260a11964b
            expiration: 86400000
