defaultTenent: tenant_1

# mybatis mapper xml path
# mybatis.mapper-locations=classpath:mappers/*.xml
mybatis:
    mapper-locations: classpath:/my/work/multitenencydatabase/demo/**/sql/*.xml
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30

# Jsp
spring:
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp

application:
    security:
        jwt:
            secret-key: 99d2485a2b601bc396cc378707ce3c6388b0d09be4c8f908f29c71260a11964b
            expiration: 86400000
